### ISSUE TITLE
Search Bar does not always expand

### ISSUE THREAD

**Issue by sp71** [yonasstephen/swift-of-airbnb#1]
Hey! This is a great project you are working on. I went into `AirbnbExploreFeedController` and changed your categories `var categories = ["Just Booked"]`. If you now try to collapse, it won't work anymore. This is an issue with the current  [michiganlabs](https://github.com/MichiganLabs/AnimatingTableViewHeader) but I left an issue there as well. Cool project

**Comment by yonasstephen** [comment]
First of all sorry for the super late follow up. It's a simple fix at below code in `BaseTableViewController.swift`:

`let absoluteBottom: CGFloat = max(0, scrollView.contentSize.height - scrollView.frame.height)`
